<?php
/*
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GNU General Public License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/gpl-license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@refersion.com so we can send you a copy immediately.
 *
 * @category   UBERCX
 * @package    Ubercx_Shippingtracking
 * @copyright  Copyright (c) 2015 Ubercx, Inc.
 * @author	   Ubercx Developer <ubercx_nospam@jframeworks.com>
 * @license    http://opensource.org/licenses/gpl-license GNU General Public License
 */
?>
<?php  $_order = $this->getOrder() ?>
<p class="order-links">
    <?php  if ($_order->getTracksCollection()->count()) : ?>
	 <!--Section added for Ubercx tracking link Start-->
    <?php if($this->isActive()):?>
    <a href="#" onclick="popWin('<?php echo $this->helper('shippingtracking')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','top=0,left=0,width=800,height=600,resizable=yes,scrollbars=yes'); return false;" title="<?php echo $this->__('Track all your shipments') ?>"><?php echo $this->__('Track all your shipments') ?></a><span class="separator">|</span>
    <?php else:?>
     <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','top=0,left=0,width=800,height=600,resizable=yes,scrollbars=yes'); return false;" title="<?php echo $this->__('Track all shipment(s)') ?>"><?php echo $this->__('Track all shipment(s)') ?></a><span class="separator">|</span>
    <?php endif;?>
    <!--Section added for Ubercx tracking link END-->
    <?php endif; ?>
    <a href="<?php echo $this->getPrintAllShipmentsUrl($_order) ?>" onclick="this.target='_blank'" class="link-print"><?php echo $this->__('Print All Shipments') ?></a>
</p>
<?php foreach ($_order->getShipmentsCollection() as $_shipment): ?>
<h2 class="sub-title"><?php echo $this->__('Shipment #') ?><?php echo $_shipment->getIncrementId(); ?> <span class="separator">|</span> <a href="<?php echo $this->getPrintShipmentUrl($_shipment) ?>" onclick="this.target='_blank'" class="link-print"><?php echo $this->__('Print Shipment') ?></a></h2>
<?php $tracks = $_shipment->getTracksCollection(); ?>
<?php  if ($tracks->count()): ?>
<table class="data-table tracking-table" id="my-tracking-table-<?php echo $_shipment->getId(); ?>">
  <tbody>
    <tr>
      <td colspan="2">
        <!--Section added for Ubercx tracking link Start-->
        <?php if($this->isActive()):?>
         <a href="#" onclick="popWin('<?php echo $this->helper('shippingtracking')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','top=0,left=0,width=800,height=600,resizable=yes,scrollbars=yes'); return false;" title="<?php echo $this->__('Track your shipment') ?>"><?php echo $this->__('Track your shipment') ?></a>
        <?php else:?>
         <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','top=0,left=0,width=800,height=600,resizable=yes,scrollbars=yes'); return false;" title="<?php echo $this->__('Track this shipment') ?>"><?php echo $this->__('Track this shipment') ?></a>
        <?php endif;?>
        <!--Section added for Ubercx tracking link END-->
      </td>
    </tr>
    <tr>
    	<th class="label"><?php echo $this->__('Tracking Number(s):') ?></th>
      <td>&nbsp;
      <?php
      $i = 1;
      $_size = $tracks->count();
      foreach($tracks as $track): ?>
      <?php if($track->isCustom()): ?>
          <?php echo $this->escapeHtml($track->getNumber()) ?>
<a href="#" onclick="popWin('<?php echo $this->helper('shippingtracking')->getTrackingPopupUrlBySalesModel($track) ?>','trackorder','width=800,height=600,left=0,top=0,resizable=yes,scrollbars=yes')" ><?php echo $this->escapeHtml($track->getNumber()) ?><?php echo $this->escapeHtml($track->getCarrierTitle()) ?></a>
      <?php else: ?>
      	<?php if($this->isActive()):?>
          <a href="#" onclick="popWin('<?php echo $this->helper('shippingtracking')->getTrackingPopupUrlBySalesModel($track) ?>','trackorder','width=800,height=600,left=0,top=0,resizable=yes,scrollbars=yes')" ><?php echo $this->escapeHtml($track->getNumber()) ?><?php echo $this->escapeHtml($track->getCarrierTitle()) ?></a>
        <?php else:?>
        	<a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($track) ?>','trackorder','width=800,height=600,left=0,top=0,resizable=yes,scrollbars=yes')" ><?php echo $this->escapeHtml($track->getNumber()) ?><?php echo $this->escapeHtml($track->getCarrierTitle()) ?></a>
        <?php endif;?>  
      <?php endif; ?>
      <?php if($i!=$_size): ?>, <?php endif; ?>
      <?php $i++;
      endforeach; ?>
      </td>
    </tr>
  </tbody>
</table>
  <script type="text/javascript">decorateTable('my-tracking-table-<?php echo $_shipment->getId(); ?>')</script>
<?php  endif; ?>
<h3 class="table-caption"><?php echo $this->__('Items Shipped') ?></h3>
<table class="data-table" id="my-shipment-table-<?php echo $_shipment->getId(); ?>">
  <col />
  <col width="1" />
  <col width="1" />
  <thead>
      <tr>
          <th><?php echo $this->__('Product Name') ?></th>
          <th><?php echo $this->__('SKU') ?></th>
          <th class="a-center"><span class="nobr"><?php echo $this->__('Qty Shipped') ?></span></th>
      </tr>
  </thead>
  <?php $_items = $_shipment->getAllItems(); ?>
  <?php $_count = count($_items) ?>
  <?php foreach ($_items as $_item): ?>
  <?php if ($_item->getOrderItem()->getParentItem()) continue; ?>
  <tbody>
      <?php echo $this->getItemHtml($_item) ?>
  </tbody>
  <?php endforeach; ?>
</table>
<script type="text/javascript">decorateTable('my-shipment-table-<?php echo $_shipment->getId(); ?>', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
<?php echo $this->getCommentsHtml($_shipment)?>
<?php endforeach; ?>
